### ISSUE TITLE
swapped up axes for online feedback

### ISSUE THREAD

**Issue by rozmar** [AllenNeuralDynamics/Aind.Behavior.ForceForaging#22]
There is an image displayed that shows the 2D LUT for closed loop feedback, and also there is a cursor that shows the current loadcell output.
It turns out that the two axes are swapped for the latter compared to the former. Also, I suspect that the Y axis will have to be reversed, too.

**Comment by bruno-f-cruz** [comment]
Superseded by work in https://github.com/AllenNeuralDynamics/Aind.Behavior.Telekinesis
