### ISSUE TITLE
quiescence_period at the end of the trial / online feedback starts only at response period?

### ISSUE THREAD

**Issue by rozmar** [AllenNeuralDynamics/Aind.Behavior.ForceForaging#23]
Right now at trial start the cursor (reward port in the BCI) returns to the starting position before/at the quiescence_period.
Then Bonsai waits until the criteria is met to go to the initiation period.
Then the reward port is operated by the mouse in the response_period, which is signified by an auditory GO cue.

The problem is that the reward port returning to the starting position is a much more salient signal than the auditory GO cue. It seems like the mice are not getting the memo that they should stop doing things in order to go through the quiescence period.

What we do in the old version of the BCI task is to check for quiescence at the end of the trial, then ITI, then the auditory GO cue and the lickport returning to the starting position happen simultaneously.

Can we do this?

Or alternatively, the reward port returns to the starting position only in the beginning of the response period? (and the quiescence period stays at the beginning of the trial) This is also good.

**Comment by bruno-f-cruz** [comment]
Superseded by work in https://github.com/AllenNeuralDynamics/Aind.Behavior.Telekinesis
