### ISSUE TITLE
define LUT for relative changes instead of absolute

### ISSUE THREAD

**Issue by rozmar** [AllenNeuralDynamics/Aind.Behavior.ForceForaging#25]
This is just an idea not a request yet. 
Nailing a given, very specific load cell value is hard, because the loadcell will have a reading already if you put your hand on it, and you have to figure out a force relative to the force you apply when you put your hand on the lever.

It's probably much more intuitive to change the forces relative to a baseline where you already have your hand on the lever. This is similar to how the original force foraging was envisioned, if I remember correctly.

Can we use the quiescent state for this? During quiescent state, we are waiting for the loadcells to reduce their variance in a given time window to be under a given variance, instead of to be under a given absolute value. The mean value in this window is going to be the origo in the next response period. ( I guess this is the hard part)

Would that be easy-ish? :)

**Comment by bruno-f-cruz** [comment]
Superseded by work in https://github.com/AllenNeuralDynamics/Aind.Behavior.Telekinesis
