### ISSUE TITLE
Action Updater for FORCE_DURATION nonfunctional

### ISSUE THREAD

**Issue by jasonyslee** [AllenNeuralDynamics/Aind.Behavior.ForceForaging#29]
Action updater for FORCE_DURATION should be updating the required hold length per trial/reward, but it remains static.
In contrast, updaters for Upper and Lower force threshold are working as expected.

Reproducible with this task_logic: 
**AindForceForagingTaskLogic_ROI_trial_test_updaters_on_reward.json**

**Comment by bruno-f-cruz** [comment]
Can you attach the json file to make it easier for us to test? thanks!

**Comment by jasonyslee** [comment]
[AindForceForagingTaskLogic_ROI_trial_test_updaters_on_reward.json](https://github.com/user-attachments/files/17723291/AindForceForagingTaskLogic_ROI_trial_test_updaters_on_reward.json)

**Comment by bruno-f-cruz** [comment]
Fixed by a604460
