### ISSUE TITLE
Load cell Calibration function unreliable

### ISSUE THREAD

**Issue by jasonyslee** [AllenNeuralDynamics/Aind.Behavior.ForceForaging#32]
Bonsai "Calibrate load cells" does not always successfully zero the load cells on first try. They may settle on a peculiarly offset value. Re-running Calibration works after 1-2 more tries, so issue is technically circumventable.
Check the logic of resistance-cycling loop.

Issue encountered so far only for DOUBLE load cell readouts (not SINGLE_AVERAGE), such as in the following task_logic:
**AindForceForagingTaskLogic_ROI_trial_test_updaters_on_reward.json**

**Comment by bruno-f-cruz** [comment]
Can you write down an SOP on how to reproduce? e.g.:
Run bonsai, open visualizer, click calibrate. 
Additionally, is it always the same load cell (i.e. first versus second)

**Comment by jasonyslee** [comment]
[AindForceForagingTaskLogic_ROI_trial_test_updaters_on_reward.json](https://github.com/user-attachments/files/17723312/AindForceForagingTaskLogic_ROI_trial_test_updaters_on_reward.json)
Same json as the Updaters issue.

SOP: 
Launch bonsai through CLABE, using task logic above.
Check that both left and right output is coming through (DOUBLE)
Enlarge visualizer window.
Click Calibrate Load Cells.
Compare left and right outputs to each other and to 0.
If left != right, or either output is far from 0, click Calibrate again.

*I can't say for sure whether it was the same load cell, as it was a stray observation from one day. I want to say both were affected but we'll see.

**Comment by bruno-f-cruz** [comment]
I dont think we managed to reproduce this last time? I will close this for now, but feel free to re-open if you find a reliable way to reproduce the issue. Thanks for reporting!
