### ISSUE TITLE
Identifying load cells connected to Champalimaud interface as part of Rig schema

### ISSUE THREAD

**Issue by jasonyslee** [AllenNeuralDynamics/Aind.Behavior.ForceForaging#33]
In the Rig schema, include function to identify the load cells currently connected to the Champalimaud interface and their channels etc.

**Comment by bruno-f-cruz** [comment]
If you mean the ones you want to use for the left and right sensor, this is already tracked here: https://github.com/AllenNeuralDynamics/Aind.Behavior.ForceForaging/blob/8cc6cc3a40dfbb81fabe03da29536b218137e898/src/DataSchemas/aind_behavior_force_foraging/task_logic.py#L380C1-L381C81
