### ISSUE TITLE
Updating trials on "reward" updates all trials after the first reward

### ISSUE THREAD

**Issue by jasonyslee** [AllenNeuralDynamics/Aind.Behavior.ForceForaging#36]
Updating trials on "reward" updates all trials after the first rewarded trial, regardless of their outcome. 
This is caused by the rewarded state remaining on, as aborted trials do not update the reward state.
Problematic code on back end identified by Bruno 11/19/24

**Comment by bruno-f-cruz** [comment]
Fixed by [679f79b](https://github.com/AllenNeuralDynamics/Aind.Behavior.ForceForaging/pull/26/commits/679f79b9e24a599cfd4ec31283e1df0bddee3255)
